name: "Sync data to S3"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
env:
  bucket: ${{ secrets.DATA_BUCKET_NAME }}
  cloudFrontDeploymentId: ${{ secrets.CLOUDFRONT_DEPLOYMENT_ID }}

jobs:
  sync:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Sync to AWS"
        run: |
          aws s3 sync --sse --delete . s3://${{ env.bucket }}  --exclude "*" --include "data/*"
          aws cloudfront create-invalidation --distribution-id ${{ env.cloudFrontDeploymentId }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
