name: "Sync data to S3"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
env:
  bucket: ${{ secrets.DATA_BUCKET_NAME }}
  cloudFrontDeploymentId: ${{ secrets.CLOUDFRONT_DEPLOYMENT_ID }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: "Sync to AWS"
        run: |
          aws s3 sync --sse --delete . s3://${{ env.bucket }}  --exclude "*" --include "data/*"
          aws cloudfront create-invalidation --distribution-id ${{ env.cloudFrontDeploymentId }} --paths "/data/*"
        env:
          AWS_DEFAULT_REGION: "eu-central-1"
