name: End-to-end tests
on:
  deployment_status:
jobs:
  run-e2e-tests:
    if: github.event.deployment_status.environment == 'Preview – volebna-kalkulacka'
    name: Run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./frontend/.nvmrc
      - name: Install dependencies
        run: |
          npm ci
      - name: Run end-to-end tests via Cypress
        env:
          PUBLIC_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          npm run test-only
