name: "Frontend: build, test & lint"
on:
  push:
    branches: main
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**
jobs:
  build:
    name: Build, test & lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Get NPM cache folder path
        id: npm-cache-folder
        run: |
          echo "::set-output name=path::$(npm config get cache)"
      - name: Set up NPM cache
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: frontend-node-modules
        with:
          path: ${{ steps.npm-cache-folder.outputs.path }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Check formatting
        run: |
          npx prettier --check .
      - name: Build
        run: |
          npm run build
      - name: Run unit tests
        run: |
          npm run test:unit
      - if: false
        name: Run end-to-end tests
        run: |
          npm run test:e2e:ci
